### ISSUE TITLE
Cancel through SelectionController mess up LocalHistory

### ISSUE THREAD

**Issue by iazel** [hcbpassos/drag_select_grid_view#31]
In my app, I can cancel selection through a button. When the button is pressed, I call `selectionController.clear()`, which will update the internal state of the Grid component through `_onSelectedChange`, but this method do not call `_updateLocalHistory`, hence the `LocalHistoryEntry` isn't removed and as soon as I pop the route, it will crash due to `setState(_selectionManager.clear);` on a disposed widget.

The fix is rather easy, but first I'd like to understand what's the need for this `LocalHistoryEntry`?

By the way, we need to add `impliesAppBarDismissal: false` to the `LocalHistoryEntry`, given that it will not dismiss the bar, at least in my case.

**Comment by hcbpassos** [comment]
hey there :)

thanks for the descriptive issue and for spotting the bug. 

> The fix is rather easy, but first I'd like to understand what's the need for this `LocalHistoryEntry`?

as you can check in [this test](https://github.com/hcbpassos/drag_select_grid_view/blob/7cf48caebf1d3e4ce0b22f35e34825de4d083a48/test/src/drag_select_grid_view/drag_select_grid_view_test.dart#L995), by adding a new entry to the local history, the widget unselects all items whenever we try to pop the route. this behavior is what causes the selection to be automagically cleared when the user taps the close button, for instance, without even needing to link the `CloseButton.onPressed` callback to the grid controller. Android's back button/gesture is another example of an action that causes the selection to be cleared due to the local history entry.

> By the way, we need to add impliesAppBarDismissal: false to the LocalHistoryEntry, given that it will not dismiss the bar, at least in my case.

sounds reasonable. i'll expose such an attribute.

**Comment by hcbpassos** [comment]
please, let me know if the last release works out for you :)

**Comment by iazel** [comment]
Thank you for updating it so soon, it works as expected and this helped me better understand `LocalHistory` :+1:
