### ISSUE TITLE
onVerticalDragDown

### ISSUE THREAD

**Issue by CauliflowerGoer** [hcbpassos/drag_select_grid_view#8]
How do I make a vertical selection?

I used a terrible way , Loop through many DragSelectGridViews in one line

![iShot2020-03-15上午04 11 14](https://user-images.githubusercontent.com/59127546/76689661-13f02980-6673-11ea-88c6-3eafe38fc92a.gif)

**Comment by hugocbpassos** [comment]
There's no such feature yet and it's impossible to aprove your approach, since a single grid is already very resource-taking.

By the way, [drag-select-recyclerview](https://github.com/afollestad/drag-select-recyclerview), my main inspiration, supports this. I thought it was useless and no one was using it, so I decided to not waste my time. Seems like I was wrong.

**Comment by hugocbpassos** [comment]
However, [drag-select-recyclerview](https://github.com/afollestad/drag-select-recyclerview) doesn't limit the selection vertically. Instead, you get to selected exclusively the items you dragged by. Is that what you are looking for?

**Comment by BreezeStark** [comment]
Very grateful for your help
